version: "3"

volumes:
  letsencrypt:
  outbuild:

services:
  node:
    build:
      context: ./server_node
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    container_name: node

  proxy:
    image: proxy-basic
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      ENVSUBST_VARS: FQDN
      FQDN: ${DOMAIN}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - outbuild:/usr/share/nginx/html
    depends_on:
      - node
    restart: always
