name: Test
on:
  push:
    branches:
      - master
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  NodeJSTest:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: ['4.4']
        python-version: ['3.6']

    steps:
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip3
          python3 -m pip install --upgrade "git+https://github.com/nficano/pytube.git" 
          pip3 install xmltodict
      
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
          
      - uses: actions/checkout@v2
      - working-directory: ./server_node
        run: |
          npm ci
          apt-get install -y python3-pip
          yarn install
      
      - name: test node server
        run: |
          yarn test
        working-directory: ./server_node
        env:
          HTTP_PORT: 4000
          MONGO_URI: mongodb://localhost:27017/dev # Access mongoDB Docker container
  
      - name: Archive code coverage results 😛
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: server_node/output/coverage/
