name: Test master branch
on:
  push:
    branches:
      - master
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  NodeJSTest:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: ['4.4']

    steps:
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
          
      - uses: actions/checkout@v2
      - working-directory: ./server_node
        run: |
          npm ci
          yarn install
      
      - name: test node server
        run: |
          yarn test
        working-directory: ./server_node
      
      - name: Archive test results 😉
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: output/test/test-report.html
            
      - name: Archive code coverage results 😛
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: output/coverage/
